spring:
  application:
    name: spring-cloud-sleuth-otel-slf4j
  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: http://otel-collector:4317
    baggage:
     remoteFields: requestId,serviceName,traceId,traceparent,testProperty
     correlationFields: requestId,serviceName,traceId,traceparent,testProperty
     tagFields: requestId,serviceName,traceId,testProperty
     localFields: serviceName
    propagation:
     type: W3C 
    